name: Feature Request
description: Suggest an idea for this project
title: "[FEATURE]: "
labels:
  - enhancement

body:
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: Describe the problem you're facing.
      placeholder: |
        I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: Explain what you would like to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: List any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context, mockups, screenshots, or examples here.
    validations:
      required: false